"use client";
import {useEffect,useState} from "react";
import {createClient} from "../../lib/supabase/client";
export default function Admin(){const s=createClient();const[items,setItems]=useState<any[]>([]),[allowed,setAllowed]=useState<boolean|null>(null);
async function load(){const a=await s.auth.getUser();if(!a.data.user){location.href="/login";return}const p=await s.from("profiles").select("role").eq("id",a.data.user.id).single();if(p.data?.role!=="admin"){setAllowed(false);return}setAllowed(true);const r=await s.from("materials").select("*").eq("status","pending").order("created_at",{ascending:false});setItems(r.data||[])}
useEffect(()=>{load()},[]);
async function approve(id:string){await s.from("materials").update({status:"approved",approved_at:new Date().toISOString(),approved_by:(await s.auth.getUser()).data.user?.id}).eq("id",id);load()}
async function reject(id:string){const reason=prompt("Rejection reason?");if(!reason)return;await s.from("materials").update({status:"rejected",rejection_reason:reason}).eq("id",id);load()}
async function remove(id:string,path:string){if(!confirm("Delete material?"))return;await s.storage.from("materials").remove([path]);await s.from("materials").delete().eq("id",id);load()}
if(allowed===null)return <main className="section"><div className="container empty">Checking admin access…</div></main>;
if(!allowed)return <main className="section"><div className="container empty"><h2>Admin access required</h2><a href="/">Back to Library</a></div></main>;
return <main className="section"><div className="container"><div className="sectionhead"><div><h1>Admin Dashboard</h1><p className="muted">Review student uploads.</p></div><a href="/" className="btn">← Library</a></div><div className="grid">{items.map(m=><article className="card" key={m.id}><h3>{m.title}</h3><p className="muted">{m.subject} · {m.exam} · {m.language} · {m.material_type}</p><p>{m.description}</p><p className="muted">{m.file_name}</p><div className="actions"><button className="btn primary" onClick={()=>approve(m.id)}>✓ Approve</button><button className="btn" onClick={()=>reject(m.id)}>Reject</button><button className="btn" onClick={()=>remove(m.id,m.storage_path)}>Delete</button></div></article>)}</div>{!items.length&&<div className="empty">No pending uploads.</div>}</div></main>}