"use client";
import {useEffect,useState} from "react";
import {createClient} from "../lib/supabase/client";
export default function Home(){
 const s=createClient();const[items,setItems]=useState<any[]>([]);const[user,setUser]=useState<any>();const[q,setQ]=useState("");
 async function load(){const a=await s.auth.getUser();setUser(a.data.user);const r=await s.from("materials").select("*").eq("status","approved").order("created_at",{ascending:false});setItems(r.data||[])}
 useEffect(()=>{load()},[]);
 const filtered=items.filter(m=>[m.title,m.subject,m.exam,m.language].join(" ").toLowerCase().includes(q.toLowerCase()));
 return <><nav className="nav"><div className="container navin"><div className="brand">MPSC <span>Library</span></div><div>{user?<button className="btn" onClick={async()=>{await s.auth.signOut();load()}}>Logout</button>:<a className="btn" href="/login">Login / Signup</a>} <button className="btn primary" onClick={()=>location.href=user?"/#upload":"/login"}>Upload Material</button></div></div></nav>
 <section className="hero"><div className="container"><div className="eyebrow">FREE • COMMUNITY • MPSC</div><h1>Free MPSC Study Material</h1><p>एक विद्यार्थी upload करेल, हजारो विद्यार्थी मोफत अभ्यास करतील.</p><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search books, notes, subjects, exams..."/></div></div></section>
 <section className="section" id="library"><div className="container"><div className="sectionhead"><h2>Study Library</h2><span className="muted">Admin-approved PDFs</span></div><div className="grid">{filtered.map(m=><article className="card" key={m.id}><div className="material"><div className="icon">📚</div><div><h3>{m.title}</h3><div className="muted">{m.subject} · {m.exam} · {m.language}</div></div></div><p className="muted">{m.description||"MPSC study material."}</p><button className="btn" onClick={()=>window.open(s.storage.from("materials").getPublicUrl(m.storage_path).data.publicUrl,"_blank")}>⬇ Read / Download PDF</button></article>)}</div>{!filtered.length&&<div className="empty">No approved material found.</div>}</div></section>
 <section className="section" id="upload"><div className="container"><div className="upload"><h2>Upload Study Material</h2><p className="muted">Login करून PDF upload करा. Admin approval नंतर ती public होईल.</p><a className="btn primary" href={user?"/upload":"/login"}>📤 Upload PDF</a></div></div></section>
 </>}