"use client";
import {useEffect,useMemo,useState} from "react";
type Material={id:string;title:string;subject:string;exam:string;language:string;type:string;description:string;fileName:string;dataUrl:string;status:"pending"|"approved";views:number;downloads:number;createdAt:string};
const seed:Material[]=[
{id:"1",title:"Maharashtra History Notes",subject:"History",exam:"Rajyaseva",language:"Marathi",type:"Notes",description:"Maharashtra history revision notes.",fileName:"",dataUrl:"",status:"approved",views:12,downloads:4,createdAt:"2026-10-03"},
{id:"2",title:"Indian Polity Quick Revision",subject:"Polity",exam:"Rajyaseva / Group B",language:"Marathi",type:"Notes",description:"Quick revision material.",fileName:"",dataUrl:"",status:"approved",views:20,downloads:8,createdAt:"2026-10-02"},
{id:"3",title:"Geography Complete Notes",subject:"Geography",exam:"Rajyaseva",language:"Marathi",type:"Notes",description:"Geography study notes.",fileName:"",dataUrl:"",status:"approved",views:9,downloads:2,createdAt:"2026-10-01"},
{id:"4",title:"MPSC Previous Year Papers 2018–2025",subject:"Previous Papers",exam:"All Exams",language:"Marathi",type:"PYQ",description:"Previous year practice papers.",fileName:"",dataUrl:"",status:"approved",views:32,downloads:15,createdAt:"2026-09-30"}];
const key="mpsc-materials";
export default function Home(){
 const [materials,setMaterials]=useState<Material[]>([]);
 const [q,setQ]=useState(""); const [filter,setFilter]=useState("All"); const [showUpload,setShowUpload]=useState(false);
 useEffect(()=>{try{const x=localStorage.getItem(key);setMaterials(x?JSON.parse(x):seed)}catch{setMaterials(seed)}},[]);
 useEffect(()=>{if(materials.length)localStorage.setItem(key,JSON.stringify(materials))},[materials]);
 const approved=materials.filter(x=>x.status==="approved");
 const filtered=useMemo(()=>approved.filter(x=>(filter==="All"||x.type===filter)&&[x.title,x.subject,x.exam,x.language].join(" ").toLowerCase().includes(q.toLowerCase())),[approved,q,filter]);
 const download=(m:Material)=>{setMaterials(ms=>ms.map(x=>x.id===m.id?{...x,downloads:x.downloads+1}:x));if(m.dataUrl){const a=document.createElement("a");a.href=m.dataUrl;a.download=m.fileName||m.title+".pdf";a.click()}else alert("या demo material साठी PDF जोडलेली नाही.");};
 return <><nav className="nav"><div className="container navin"><div className="brand">MPSC <span>Library</span></div><div className="navlinks"><a href="#home">Home</a><a href="#library">Study Material</a><a href="#upload">Upload</a><a href="#about">About</a></div><a className="btn primary" href="#upload">Upload Material</a></div></nav>
 <main id="home"><section className="hero"><div className="container"><div className="eyebrow">FREE • COMMUNITY • MPSC</div><h1>Free MPSC Study Material</h1><p>एक विद्यार्थी upload करेल, हजारो विद्यार्थी मोफत अभ्यास करतील.</p><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search books, notes, subjects, exams..." /><button className="btn primary">Search</button></div></div></section>
 <section className="section" id="library"><div className="container"><div className="sectionhead"><div><h2>Study Library</h2><p className="muted">Approved material • Free access</p></div><div className="chips">{["All","Books","Notes","PYQ"].map(x=><button key={x} className={"chipbtn "+(filter===x?"active":"")} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="grid">{filtered.map(m=><article className="card" key={m.id}><div className="material"><div className="icon">{m.type==="PYQ"?"📄":m.type==="Books"?"📚":"📝"}</div><div><h3>{m.title}</h3><div className="muted">{m.subject} · {m.exam}</div><div className="chips"><span className="chip">{m.language}</span><span className="chip">FREE</span></div></div></div><p className="muted">{m.description}</p><div className="actions"><button className="btn" onClick={()=>download(m)}>⬇ Download</button><span className="muted">👁 {m.views} · ⬇ {m.downloads}</span></div></article>)}</div>{!filtered.length&&<div className="empty">No approved material found.</div>}</div></section>
 <section className="section" id="upload"><div className="container"><div className="upload"><h2>Upload Study Material</h2><p className="muted">PDF upload केल्यानंतर ते आधी <b>Pending</b> राहील. Admin approval नंतरच public library मध्ये दिसेल.</p><button className="btn primary" onClick={()=>setShowUpload(true)}>📤 Upload PDF</button></div></div></section>
 <section className="section" id="about"><div className="container"><div className="card"><h2>How it works</h2><div className="steps"><div><b>1. Upload</b><span>Student uploads original/use-authorized material.</span></div><div><b>2. Review</b><span>Admin checks the submission.</span></div><div><b>3. Publish</b><span>Approved material becomes free for everyone.</span></div></div></div></div></section></main>
 {showUpload&&<Upload onClose={()=>setShowUpload(false)} onAdd={m=>setMaterials(ms=>[m,...ms])}/>}
 <footer className="footer"><div className="container">© 2026 MPSC Library · Free educational community</div></footer></>}
function Upload({onClose,onAdd}:{onClose:()=>void;onAdd:(m:Material)=>void}){const [f,setF]=useState({title:"",subject:"",exam:"Rajyaseva",language:"Marathi",type:"Notes",description:""});const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!f.title||!file)return alert("Title आणि PDF आवश्यक आहे.");if(file.type!=="application/pdf")return alert("फक्त PDF upload करा.");if(file.size>15*1024*1024)return alert("PDF 15MB पेक्षा कमी असावी.");setBusy(true);const reader=new FileReader();reader.onload=()=>{onAdd({id:crypto.randomUUID(),...f,fileName:file.name,dataUrl:String(reader.result),status:"pending",views:0,downloads:0,createdAt:new Date().toISOString()});setBusy(false);alert("Material submitted for admin approval.");onClose()};reader.readAsDataURL(file)};
 return <div className="modal"><form className="modalbox" onSubmit={submit}><div className="sectionhead"><h2>Upload PDF</h2><button type="button" className="x" onClick={onClose}>×</button></div><input required placeholder="Material title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><div className="twocol"><input required placeholder="Subject" value={f.subject} onChange={e=>setF({...f,subject:e.target.value})}/><select value={f.exam} onChange={e=>setF({...f,exam:e.target.value})}><option>Rajyaseva</option><option>Group B</option><option>Group C</option><option>PSI</option><option>STI</option><option>ASO</option></select></div><div className="twocol"><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>Notes</option><option>Books</option><option>PYQ</option></select><select value={f.language} onChange={e=>setF({...f,language:e.target.value})}><option>Marathi</option><option>English</option></select></div><textarea placeholder="Short description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><input required type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={busy} className="btn primary">{busy?"Uploading…":"Submit for Review"}</button></form></div>}